-- 20260902110000_consolidate_scans_select_policy.sql
--   PENDING: NOT APPLIED, awaiting approval. RLS change - review carefully.
--
-- Collapse two functionally identical SELECT policies on public.scans into one.
--
-- ---------------------------------------------------------------------------
-- WHAT IS THERE NOW (from supabase/schemas/public/tables/scans.sql)
-- ---------------------------------------------------------------------------
-- Two SELECT policies, doing the same job in different SQL:
--
--   scans_select_same_org   TO authenticated
--     USING (EXISTS (SELECT 1 FROM assets a
--                     WHERE a.id = scans.asset_id
--                       AND a.organization_id IN (SELECT u.organization_id
--                                                   FROM users u
--                                                  WHERE u.id = auth.uid())))
--
--   users_view_org_scans    TO PUBLIC
--     USING (auth.uid() IS NOT NULL
--            AND asset_id IN (SELECT assets.id FROM assets
--                              WHERE assets.organization_id IN
--                                    (SELECT users.organization_id FROM users
--                                      WHERE users.id = auth.uid())))
--
-- ---------------------------------------------------------------------------
-- WHAT EACH ONE ACTUALLY GRANTS  (measured 2026-09-02, not inferred)
-- ---------------------------------------------------------------------------
-- To an ANONYMOUS caller: NOTHING, from either policy.
--
--   scans_select_same_org is granted TO authenticated. anon is not in that
--   role, so it never applies.
--
--   users_view_org_scans is granted TO PUBLIC, which does include anon -- but
--   its first condition is `auth.uid() IS NOT NULL`, and auth.uid() is NULL
--   for anon. It fails on the first clause.
--
-- Probed against production with the anon key, the request does not even reach
-- those policies. It fails earlier with:
--
--   401  permission denied for function get_my_organization_id
--
-- Both policies subquery public.users, and the users table's own policy calls
-- public.get_my_organization_id(), which is REVOKEd FROM PUBLIC and granted
-- only to authenticated. So anon is stopped by a function grant one layer
-- below RLS. Worth knowing: the anon block does not depend on the text of
-- either scans policy.
--
-- To an AUTHENTICATED caller: their own organization's scans, from BOTH
-- policies, identically. Verified: a EuroRent admin sees 333 of the 337 scan
-- rows in the database -- that organization owns most of them -- and not the
-- other 4.
--
-- ---------------------------------------------------------------------------
-- WHY CONSOLIDATE
-- ---------------------------------------------------------------------------
-- This is dead weight and a correctness hazard, not a live vulnerability.
--
--   * Postgres ORs permissive policies, so BOTH subqueries are evaluated for
--     every candidate row. Two identical checks, twice the work.
--   * Two policies expressing one rule means a future edit can tighten one and
--     leave the other quietly granting the old access. That is how an
--     isolation bug gets shipped by someone who believed they had fixed it.
--   * `TO PUBLIC` on a tenant table reads alarmingly in an audit even though
--     the auth.uid() guard makes it safe. Removing it removes the question.
--
-- The kept policy is scans_select_same_org: it is scoped TO authenticated
-- rather than PUBLIC, so it does not rely on an internal null check to exclude
-- anonymous callers, and EXISTS expresses the intent more directly than IN.
--
-- ---------------------------------------------------------------------------
-- RISK
-- ---------------------------------------------------------------------------
-- Dropping a policy can only ever REMOVE access, never add it. Since both
-- policies grant the same set, dropping the redundant one changes no caller's
-- visibility. The measurements above are the evidence for that claim; re-run
-- them after applying and the numbers should be identical.
--
-- INSERT is untouched: scans_insert_public_qr_log stays exactly as it is, and
-- it is the policy that lets an anonymous QR scan log itself.

BEGIN;

DROP POLICY IF EXISTS "users_view_org_scans" ON public.scans;

COMMIT;

-- ---------------------------------------------------------------------------
-- VERIFY AFTER APPLYING
-- ---------------------------------------------------------------------------
-- 1. Exactly two policies remain: one SELECT, one INSERT.
--
--   SELECT policyname, cmd, roles
--   FROM pg_policies
--   WHERE schemaname = 'public' AND tablename = 'scans'
--   ORDER BY cmd, policyname;
--
--   Expect scans_insert_public_qr_log (INSERT) and
--          scans_select_same_org      (SELECT, {authenticated}).
--
-- 2. An authenticated user sees the SAME count as before. Signed in as a
--    EuroRent member that was 333 of 337 on 2026-09-02:
--
--   SELECT count(*) FROM public.scans;
--
-- 3. An anonymous request still reads nothing:
--
--   curl "$SUPABASE_URL/rest/v1/scans?select=id&limit=1" -H "apikey: $ANON_KEY"
--
--   Expect a 401. Note it currently fails on the get_my_organization_id grant
--   rather than on RLS, so this checks the outcome, not the mechanism.
--
-- 4. A public QR scan can still log itself: open /scan/<code> anonymously and
--    confirm a new scans row appears. That exercises the INSERT policy this
--    migration does not touch.
--
-- ---------------------------------------------------------------------------
-- NOT DONE HERE, DELIBERATELY
-- ---------------------------------------------------------------------------
-- Finding 02.4 also notes that scans has no organization_id column, so tenant
-- isolation rests on a correlated subquery through assets. Denormalising that
-- column would make this policy a simple equality and remove the subquery.
--
-- Not now: at 337 rows the current policy is trivially cheap (revised to P2 in
-- the audit), and adding a column plus a backfill plus a trigger to keep it in
-- step is a much larger change than deleting a redundant policy. Revisit when
-- scan volume is measured in six figures.
